In [1]:
import numpy as np
from itertools import combinations

In [2]:
puzzle_input = """
...#......
.......#..
#.........
..........
......#...
.#........
.........#
..........
.......#..
#...#.....
"""

In [3]:
split = puzzle_input.strip().split("\n")
grid = [[0 if x == "." else 1 for x in s] for s in split]
grid

[[0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
 [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
 [1, 0, 0, 0, 1, 0, 0, 0, 0, 0]]

In [4]:
grid = np.array(grid)
grid

array([[0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [1, 0, 0, 0, 1, 0, 0, 0, 0, 0]])

In [5]:
np.sum(grid, axis=1)

array([1, 1, 1, 0, 1, 1, 1, 0, 1, 2])

In [6]:
rows = [i for i, x in enumerate(np.sum(grid, axis=1)) if x == 0]
rows

[3, 7]

In [7]:
cols = [i for i, x in enumerate(np.sum(grid, axis=0)) if x == 0]
cols

[2, 5, 8]

In [8]:
# Add rows
expanded = np.insert(grid, rows, values=[0], axis=0)

# Add columns. These are unchanged
expanded = np.insert(expanded, cols, values=[0], axis=1)

In [9]:
expanded.shape

(12, 13)

In [10]:
x, y = np.nonzero(expanded)

In [11]:
result = []

for i, j in combinations(zip(x, y), 2):
    x_0, y_0 = i
    x_1, y_1 = j
    result.append(abs(x_0 - x_1) + abs(y_0 - y_1))

sum(result)

374

# Part 1

In [69]:
with open("inputs/11.txt") as f:
    puzzle_input = f.read()

# Part 2

In [18]:
# Add rows
expanded = grid.copy()
expansion = 1000000 - 1

for i, r in enumerate(rows):
    print(i, r)
    expanded = np.insert(
        expanded, r + i * expansion, values=np.zeros((expansion, 10)), axis=0
    )

expanded

0 3
1 7


array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 1, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 1, 0, 0],
       [1, 0, 0, ..., 0, 0, 0]])

In [14]:
from scipy import sparse

In [13]:
sparse.

AttributeError: module 'scipy' has no attribute 'sparse'

In [ ]:
l = expanded.shape[0]

# Add columns.
for i, r in enumerate(cols):
    print(i, r)
    expanded = np.insert(
        expanded, r + i * expansion, values=np.zeros((expansion, l)), axis=1
    )

expanded

0 2


In [17]:
x, y = np.nonzero(expanded)

result = []

for i, j in combinations(zip(x, y), 2):
    x_0, y_0 = i
    x_1, y_1 = j
    result.append(abs(x_0 - x_1) + abs(y_0 - y_1))

sum(result)

8410